name: compileTests

on:
  push:
    branches:
      - main

jobs:
  cTest:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Build Tests
        run: |
          javac -cp ".:Projects/P3/tests/junit-4.10.jar" Projects/P3/src/*.java
          javac -cp "Projects/P3/src/:.:Projects/P3/tests/junit-4.10.jar" Projects/P3/tests/*.java
          cat Projects/P3/src/Ghost.java
  testGetLoc:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Build Tests
        run: |
          javac -cp ".:Projects/P3/tests/junit-4.10.jar" Projects/P3/src/*.java
          javac -cp "Projects/P3/src/:.:Projects/P3/tests/junit-4.10.jar" Projects/P3/tests/*.java
          cd Projects/P3/
          java -Djava.awt.headless=true -cp "src/:tests/:tests/junit-4.10.jar" org.junit.runner.JUnitCore TestMapGetLoc
  testPacmanValidMoves:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Build Tests
        run: |
          javac -cp ".:Projects/P3/tests/junit-4.10.jar" Projects/P3/src/*.java
          javac -cp "Projects/P3/src/:.:Projects/P3/tests/junit-4.10.jar" Projects/P3/tests/*.java
          cd Projects/P3/
          java -cp "src/:tests/:tests/junit-4.10.jar" org.junit.runner.JUnitCore TestPacManValidMoves
          
  testGhostIsPacmanInRange:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Build Tests
        run: |
          javac -cp ".:Projects/P3/tests/junit-4.10.jar" Projects/P3/src/*.java
          javac -cp "Projects/P3/src/:.:Projects/P3/tests/junit-4.10.jar" Projects/P3/tests/*.java
          cd Projects/P3/
          java -cp "src/:tests/:tests/junit-4.10.jar" org.junit.runner.JUnitCore TestPacManInRange

  testEatCookie:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Build Tests
        run: |
          javac -cp ".:Projects/P3/tests/junit-4.10.jar" Projects/P3/src/*.java
          javac -cp "Projects/P3/src/:.:Projects/P3/tests/junit-4.10.jar" Projects/P3/tests/*.java
          cd Projects/P3/
          java -cp "src/:tests/:tests/junit-4.10.jar" org.junit.runner.JUnitCore TestMapEatCookie

  testGhostValidMoves:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Build Tests
        run: |
          javac -cp ".:Projects/P3/tests/junit-4.10.jar" Projects/P3/src/*.java
          javac -cp "Projects/P3/src/:.:Projects/P3/tests/junit-4.10.jar" Projects/P3/tests/*.java
          cd Projects/P3/
          java -cp "src/:tests/:tests/junit-4.10.jar" org.junit.runner.JUnitCore TestGhostValidMoves

  testGhostInRange:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Build Tests
        run: |
          javac -cp ".:Projects/P3/tests/junit-4.10.jar" Projects/P3/src/*.java
          javac -cp "Projects/P3/src/:.:Projects/P3/tests/junit-4.10.jar" Projects/P3/tests/*.java
          cd Projects/P3/
          java -cp "src/:tests/:tests/junit-4.10.jar" org.junit.runner.JUnitCore TestGhostInRange       
          
  testAttack:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Build Tests
        run: |
          cd Projects/P3/
          javac src/*.java
          javac -cp "src/:tests/junit-4.10.jar" tests/*.java
          java -Djava.awt.headless=true -cp "src/:tests/:tests/junit-4.10.jar" org.junit.runner.JUnitCore TestAttack

  testMapAttack:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Build Tests
        run: |
          javac -cp ".:Projects/P3/tests/junit-4.10.jar" Projects/P3/src/*.java
          javac -cp "Projects/P3/src/:.:Projects/P3/tests/junit-4.10.jar" Projects/P3/tests/*.java
          cd Projects/P3/
          java -cp "src/:tests/:tests/junit-4.10.jar" org.junit.runner.JUnitCore TestMapAttack

  testPacManMove:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Build Tests
        run: |
          javac -cp ".:Projects/P3/tests/junit-4.10.jar" Projects/P3/src/*.java
          javac -cp "Projects/P3/src/:.:Projects/P3/tests/junit-4.10.jar" Projects/P3/tests/*.java
          cd Projects/P3/
          java -cp "src/:tests/:tests/junit-4.10.jar" org.junit.runner.JUnitCore TestPacManMove

  testPacManConsume:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Build Tests
        run: |
          javac -cp ".:Projects/P3/tests/junit-4.10.jar" Projects/P3/src/*.java
          javac -cp "Projects/P3/src/:.:Projects/P3/tests/junit-4.10.jar" Projects/P3/tests/*.java
          cd Projects/P3/
          java -cp "src/:tests/:tests/junit-4.10.jar" org.junit.runner.JUnitCore TestPacManConsume

  testMapMove:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Build Tests
        run: |
          javac -cp ".:Projects/P3/tests/junit-4.10.jar" Projects/P3/src/*.java
          javac -cp "Projects/P3/src/:.:Projects/P3/tests/junit-4.10.jar" Projects/P3/tests/*.java
          cd Projects/P3/
          java -cp "src/:tests/:tests/junit-4.10.jar" org.junit.runner.JUnitCore TestMapMove

  testGhostMove:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Build Tests
        run: |
          javac -cp ".:Projects/P3/tests/junit-4.10.jar" Projects/P3/src/*.java
          javac -cp "Projects/P3/src/:.:Projects/P3/tests/junit-4.10.jar" Projects/P3/tests/*.java
          cd Projects/P3/
          java -cp "src/:tests/:tests/junit-4.10.jar" org.junit.runner.JUnitCore TestGhostMove

